### ISSUE TITLE
Missing weekdays and time periods

### ISSUE THREAD

**Issue by idemus** [lnNgyn1/PeriodInsertBundle#1]
Hi,
I'm very glad that the period-Insert plugin is available again for Kimai 2.0.
But I'm missing the option to select specific weekdays and a specific time period for the mass creation.
E.g. I want to insert from 1.1. - 31.1. every Monday and Wednesday the time slice from 8 am to 11:30 am.

Would it be possible to adjust this?

Best regards
Klaus

**Comment by lnNgyn1** [comment]
Hi, thanks for opening this issue! The original plugin did not have those features, so this would be a new addition. It would probably be best to make a new plugin for this. I think your suggestion would be possible in that you could select multiple days rather than a range. I'd have to make a new data type in Kimai for this. For now, I can add the time slice component to this existing plugin if that helps. Would that be okay?

**Comment by idemus** [comment]
Hi,
I've had the former plugin. Here are some screenshots how it was realized. It was quite good. 
![Screenshot_20240130_201257_Microsoft 365 (Office)](https://github.com/lnNgyn1/PeriodInsertBundle/assets/71780381/cc2ef476-7a27-4278-a87d-dff5ff554945)
![Screenshot_20240130_201322_Microsoft 365 (Office)](https://github.com/lnNgyn1/PeriodInsertBundle/assets/71780381/81393566-3ff7-4550-94a2-5bdcb53c33cc)

**Comment by lnNgyn1** [comment]
Okay, I see! My company removed that feature from the plugin, but I should be able to add it back again. I'll try to update it by the end of this week!

**Comment by lnNgyn1** [comment]
Okay, I updated the plugin to select specific days for a specified time period. I am working on adding the begin field. I'll let you know when I've finished adding that component.

**Comment by lnNgyn1** [comment]
@idemus I've updated the plugin to select specific days for a time period and added the begin time field. Let me know if you have any problems or suggestions!

**Comment by idemus** [comment]
Just installed. It works perfect. Thank for your adjustment and the fast implementation! :)
