### ISSUE TITLE
Trouble installing the plug in

### ISSUE THREAD

**Issue by kbkozlev** [lnNgyn1/PeriodInsertBundle#6]
Hi I'm having trouble installing the plugin I wget-ed the [Source Code of v1.2](https://github.com/lnNgyn1/PeriodInsertBundle/archive/refs/tags/1.2.zip) into the plugin directory and I unzipped it. After that I cleared the cache as mentioned in the instructions, but the plugin does not show up.
![image](https://github.com/user-attachments/assets/cdfe44c2-d844-4ff0-a4bc-62b11bee2c93)

**Comment by lnNgyn1** [comment]
Hi, thanks for opening this issue! I followed the same steps to install the plugin as you described, and it seems that the issue is a naming one. When you unzip the `1.2.zip` file from wget, it returns the directory `PeriodInsertBundle-1.2`. When you reload the cache, Kimai does not recognize the plugin because it is not the right name for the plugin! Rename the directory to `PeriodInsertBundle` and reload the cache. That should fix your installation issue!

**Comment by kbkozlev** [comment]
Thank you this solved the issue.
